source 'https://rubygems.org'

#Specify your gem's dependencies in layback.gemspec
# gemspec
gem 'sinatra'
gem 'thin'
gem 'layback'
gem 'json'

group :development, :test do
  gem "rake"
  gem "rspec"
  gem 'jazz_fingers'
end
